In [ ]:
##0 'brew'
##1 'water'
##2 'drink'
##3 'pour'
##4 'hold'
##5 'open'
##6 'clean'
##7 'close'
##8 'season'
##9 'serve'
##10 'heat'

In [1]:
# Load 
# Concatenation of activity and location

print("HiHi")

import numpy as np

mainPath = "/raid/home/labuseraber/environment/testEnvironment/OnlineECParser/lp/metrics/"

intenPredictedYDXJ0133  = np.loadtxt(mainPath + 'intenPredicted.txt')
intenRealYDXJ0133       = np.loadtxt(mainPath + 'intenReal.txt')

print("intenPredictedYDXJ0133 shape", intenPredictedYDXJ0133.shape)
print("intenRealYDXJ0133 shape", intenRealYDXJ0133.shape)

HiHi
intenPredictedYDXJ0133 shape (17596,)
intenRealYDXJ0133 shape (17596,)


In [3]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np
from numpy import savetxt

LABELS = ["brew", "water", "drink", "pour", "hold", "open", "clean", "close", "season", "serve", "heat"]

A = intenPredictedYDXJ0133
B = intenRealYDXJ0133

print("\nAccuracy of Reasoning: ", accuracy_score(A, B), "\n--------------------------------------------------------")
print("\nConfusion matrix:\n\n", confusion_matrix(A, B), "\n--------------------------------------------------------")
print("\nClassification report:\n\n", classification_report(A, B, digits=4), "\n--------------------------------------------------------\n--------------------------------------------------------\n--------------------------------------------------------")


Accuracy of Reasoning:  0.897306205955899 
--------------------------------------------------------

Confusion matrix:

 [[  501     0    87     0     0     0   239     0     0   104    28]
 [    0     9     0     0     0     0     0     0     0     0     0]
 [    0     0    26     0     0     0     0     0     0     0     0]
 [    0     0     0   821   234     0     0     0     0     0     0]
 [    0     0     0     0 11306   109   664     0     0     0     0]
 [    0     0     0     0    68   999   138     0     0     0     0]
 [    0     0     0     0   136     0  1142     0     0     0     0]
 [    0     0     0     0     0     0     0   356     0     0     0]
 [    0     0     0     0     0     0     0     0   542     0     0]
 [    0     0     0     0     0     0     0     0     0    38     0]
 [    0     0     0     0     0     0     0     0     0     0    49]] 
--------------------------------------------------------

Classification report:

               precision    recall 